openapi: 3.0.3
info:
  title: API de Gerenciamento de Contatos
  description: Sistema de cadastro de contatos com integração Via CEP e Google Maps
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor de desenvolvimento

tags:
  - name: Autenticação
    description: Endpoints de autenticação e cadastro de usuários
  - name: Contatos
    description: Gerenciamento de contatos
  - name: Endereços
    description: Busca de endereços via CEP
  - name: Conta
    description: Gerenciamento de conta do usuário

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    UsuarioRegistroRequest:
      type: object
      required:
        - nome
        - email
        - senha
      properties:
        nome:
          type: string
          example: João Silva
        email:
          type: string
          format: email
          example: joao@example.com
        senha:
          type: string
          format: password
          minLength: 6
          example: senha123
    
    LoginRequest:
      type: object
      required:
        - email
        - senha
      properties:
        email:
          type: string
          format: email
          example: joao@example.com
        senha:
          type: string
          format: password
          example: senha123
    
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        tipo:
          type: string
          example: Bearer
        usuario:
          $ref: '#/components/schemas/UsuarioResponse'
    
    UsuarioResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: João Silva
        email:
          type: string
          example: joao@example.com
    
    ContatoRequest:
      type: object
      required:
        - nome
        - cpf
        - telefone
        - cep
        - logradouro
        - numero
        - bairro
        - cidade
        - estado
        - latitude
        - longitude
      properties:
        nome:
          type: string
          example: Maria Santos
        cpf:
          type: string
          pattern: '^\d{11}$'
          example: '12345678901'
        telefone:
          type: string
          example: '41999887766'
        cep:
          type: string
          pattern: '^\d{8}$'
          example: '80010000'
        logradouro:
          type: string
          example: Rua das Flores
        numero:
          type: string
          example: '123'
        complemento:
          type: string
          nullable: true
          example: Apto 45
        bairro:
          type: string
          example: Centro
        cidade:
          type: string
          example: Curitiba
        estado:
          type: string
          minLength: 2
          maxLength: 2
          example: PR
        latitude:
          type: number
          format: double
          example: -25.4284
        longitude:
          type: number
          format: double
          example: -49.2733
    
    ContatoResponse:
      allOf:
        - $ref: '#/components/schemas/ContatoRequest'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
    
    ContatoPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ContatoResponse'
        totalElements:
          type: integer
          format: int64
          example: 50
        totalPages:
          type: integer
          example: 5
        size:
          type: integer
          example: 10
        number:
          type: integer
          example: 0
    
    ViaCepResponse:
      type: object
      properties:
        cep:
          type: string
          example: '80010-000'
        logradouro:
          type: string
          example: Rua das Flores
        complemento:
          type: string
          example: ''
        bairro:
          type: string
          example: Centro
        localidade:
          type: string
          example: Curitiba
        uf:
          type: string
          example: PR
        ibge:
          type: string
          example: '4106902'
        gia:
          type: string
          example: ''
        ddd:
          type: string
          example: '41'
        siafi:
          type: string
          example: '7535'
    
    EnderecoSearchResponse:
      type: array
      items:
        $ref: '#/components/schemas/ViaCepResponse'
    
    DeletarContaRequest:
      type: object
      required:
        - senha
      properties:
        senha:
          type: string
          format: password
          example: senha123
    
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: CPF inválido
        path:
          type: string
          example: /api/contatos

paths:
  /auth/registro:
    post:
      tags:
        - Autenticação
      summary: Registrar novo usuário
      description: Cria uma nova conta de usuário no sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRegistroRequest'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioResponse'
        '400':
          description: Dados inválidos ou email já cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /auth/login:
    post:
      tags:
        - Autenticação
      summary: Realizar login
      description: Autentica o usuário e retorna token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /contatos:
    get:
      tags:
        - Contatos
      summary: Listar contatos do usuário
      description: Retorna lista paginada e ordenada de contatos com filtro opcional
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          description: Filtro por nome ou CPF
          required: false
          schema:
            type: string
            example: Maria
        - name: page
          in: query
          description: Número da página (começa em 0)
          required: false
          schema:
            type: integer
            default: 0
            example: 0
        - name: size
          in: query
          description: Quantidade de itens por página
          required: false
          schema:
            type: integer
            default: 10
            example: 10
        - name: sort
          in: query
          description: Campo e direção de ordenação
          required: false
          schema:
            type: string
            default: nome,asc
            example: nome,asc
      responses:
        '200':
          description: Lista de contatos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContatoPageResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    post:
      tags:
        - Contatos
      summary: Criar novo contato
      description: Cadastra um novo contato para o usuário autenticado
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContatoRequest'
      responses:
        '201':
          description: Contato criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContatoResponse'
        '400':
          description: Dados inválidos ou CPF duplicado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /contatos/{id}:
    get:
      tags:
        - Contatos
      summary: Buscar contato por ID
      description: Retorna os dados de um contato específico
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID do contato
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Dados do contato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContatoResponse'
        '404':
          description: Contato não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    put:
      tags:
        - Contatos
      summary: Atualizar contato
      description: Atualiza os dados de um contato existente
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID do contato
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContatoRequest'
      responses:
        '200':
          description: Contato atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContatoResponse'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Contato não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    delete:
      tags:
        - Contatos
      summary: Deletar contato
      description: Remove um contato da base de dados
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID do contato
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Contato deletado com sucesso
        '404':
          description: Contato não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /enderecos/cep/{cep}:
    get:
      tags:
        - Endereços
      summary: Buscar endereço por CEP
      description: Consulta endereço via ViaCEP (proxy)
      security:
        - bearerAuth: []
      parameters:
        - name: cep
          in: path
          description: CEP sem formatação (8 dígitos)
          required: true
          schema:
            type: string
            pattern: '^\d{8}$'
            example: '80010000'
      responses:
        '200':
          description: Endereço encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViaCepResponse'
        '404':
          description: CEP não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /enderecos/search:
    get:
      tags:
        - Endereços
      summary: Buscar endereços
      description: Busca endereços por UF, cidade e logradouro via ViaCEP
      security:
        - bearerAuth: []
      parameters:
        - name: uf
          in: query
          description: UF (2 letras)
          required: true
          schema:
            type: string
            minLength: 2
            maxLength: 2
            example: PR
        - name: cidade
          in: query
          description: Nome da cidade
          required: true
          schema:
            type: string
            example: Curitiba
        - name: logradouro
          in: query
          description: Trecho do logradouro (mínimo 3 caracteres)
          required: true
          schema:
            type: string
            minLength: 3
            example: Flores
      responses:
        '200':
          description: Lista de endereços encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnderecoSearchResponse'
        '400':
          description: Parâmetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /conta:
    post:
      tags:
        - Conta
      summary: Deletar conta do usuário
      description: Remove a conta do usuário e todos seus contatos (requer senha)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletarContaRequest'
      responses:
        '204':
          description: Conta deletada com sucesso
        '401':
          description: Senha inválida ou não autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'